FROM ubuntu:xenial
MAINTAINER Panos Mavrogiorgos otinanai90@yopmail.com

RUN apt-get update \
 && apt-get install \
        -y \
        --no-install-recommends \
        --no-install-suggests \
        apt-transport-https \
        software-properties-common \
 && add-apt-repository -y ppa:saiarcot895/myppa \
 && apt-get update \
 && apt-get install \
        -y \
        --no-install-recommends \
        --no-install-suggests \
        apt-fast \
 && apt-fast install \
        -y \
        --no-install-recommends \
        --no-install-suggests \
        build-essential \
        libcurl4-openssl-dev \
        libffi-dev \
        libssl-dev \
        libpq-dev \
        git \
        vim \
        curl \
        wget \
        ruby \
        less \
        python \
        python-dev \
        ca-certificates \
        python-pip \
        silversearcher-ag \
        zsh \
 # cleanup
 #&& apt-get autoremove -y \
 #&& apt-get clean \
 #&& rm -rf /var/lib/apt/lists/* \
           #/var/tmp/* \
           #/tmp/*
 && git clone https://github.com/pmav99/dotfiles.git /root/dotfiles \
 && /root/dotfiles/install_zsh.sh \
 && chsh -s `which zsh` \
 && mkdir -p ~/.wheelhouse \
 # locale
 && locale-gen en_US en_US.UTF-8

ENTRYPOINT ["/bin/zsh"]
